# version: '3.8'

services:
  club_proxy:
    image: nginx:stable-alpine
    container_name: club_manager_proxy
    ports:
      - "${PROXY_PORT:-80}:80"
      - "443:443"
    volumes:
      - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/landing:/usr/share/nginx/html/landing:ro
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

    depends_on:
      - club_backend
      - club_frontend
    restart: unless-stopped
    networks:
      - default
      - expenses_network

  club_db:
    image: postgres:15-alpine
    container_name: club_manager_db
    volumes:
      # Mantenemos 'postgres_data' para no perder tus datos actuales
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-expenseuser} -d ${POSTGRES_DB:-expensedb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  club_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: club_manager_backend
    volumes:
      - ./backend:/code/backend
      - ./.env:/code/.env
    depends_on:
      club_db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  club_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: club_manager_frontend
    restart: unless-stopped

  club_certbot:
    image: certbot/certbot
    container_name: club_manager_certbot
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  # Este es el nombre del volumen f√≠sico en tu Droplet. No lo cambies.
  postgres_data:

networks:
  expenses_network:
    external: true
